<%!
from asvab.filters import date
%>
email: qmm-dev@google.com

jobs:
  - id: saw
    homedir: /usr/local/google/dash/sawmill/gmail
    env:
      USER: jsilverstein
    script: ./sawGmail.pl -saw ${'yesterday' | date('%Y-%m-%d')} ${'yesterday' | date('%Y-%m-%d')}

jobs:
  - id: dump
    homedir: /usr/local/google/dash/sawmill/gmail
    env:
      USER: jsilverstein
    script: ./sawGmail.pl -dump ${'yesterday' | date('%Y-%m-%d')} ${'yesterday' | date('%Y-%m-%d')} /etc/dash/data/gmail
    depends_on: saw


jobs:
  - id: load
    homedir: /usr/local/google/dash/sawmill/gmail
    env:
      USER: jsilverstein
    script: ./sawGmail.pl -load ${'yesterday' | date('%Y-%m-%d')} ${'yesterday' | date('%Y-%m-%d')} /etc/dash/data/gmail
    depends_on: dump


jobs:
  - id: delete
    homedir: /usr/local/google/dash/sawmill/gmail
    env:
      USER: jsilverstein
    script: ./sawGmail.pl -delete ${'yesterday' | date('%Y-%m-%d')} ${'yesterday' | date('%Y-%m-%d')}
    depends_on: load
